-- Plate geometry metadata (bounding box in model units + triangle count). Additive and nullable.
-- (Prisma's autogenerated diff also tried to drop the searchVector GIN indexes / defaults on the
-- hand-maintained generated tsvector columns — removed by hand, same as earlier migrations.)

-- AlterTable
ALTER TABLE "Plate" ADD COLUMN     "dimXmm" DOUBLE PRECISION,
ADD COLUMN     "dimYmm" DOUBLE PRECISION,
ADD COLUMN     "dimZmm" DOUBLE PRECISION,
ADD COLUMN     "triangleCount" INTEGER;
