-- Add targeted sharing (PrintShare / CollectionShare) and async plate processing (ProcessingJob
-- + Plate.processingStatus). Purely additive and reversible.
--
-- NOTE: Prisma's autogenerated diff also tried to DROP the searchVector GIN indexes and DROP DEFAULT
-- on the generated tsvector columns (Print.searchVector / Collection.searchVector). Those columns
-- are hand-maintained GENERATED columns (see 20260919164610_add_search_vectors) that Prisma can't
-- model, so that diff is spurious. Those statements were removed by hand: they would have deleted
-- the full-text search indexes, and DROP DEFAULT on a generated column fails outright.

-- CreateEnum
CREATE TYPE "PlateProcessingStatus" AS ENUM ('QUEUED', 'PROCESSING', 'READY', 'FAILED');

-- CreateEnum
CREATE TYPE "ProcessingJobStatus" AS ENUM ('QUEUED', 'RUNNING', 'DONE', 'ERROR');

-- AlterTable: existing plates default to READY (they already have their files/thumbnails).
ALTER TABLE "Plate" ADD COLUMN     "processingError" TEXT,
ADD COLUMN     "processingStatus" "PlateProcessingStatus" NOT NULL DEFAULT 'READY';

-- CreateTable
CREATE TABLE "PrintShare" (
    "id" TEXT NOT NULL,
    "printId" TEXT NOT NULL,
    "sharedWithUserId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "PrintShare_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "CollectionShare" (
    "id" TEXT NOT NULL,
    "collectionId" TEXT NOT NULL,
    "sharedWithUserId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CollectionShare_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ProcessingJob" (
    "id" TEXT NOT NULL,
    "plateId" TEXT NOT NULL,
    "status" "ProcessingJobStatus" NOT NULL DEFAULT 'QUEUED',
    "attempts" INTEGER NOT NULL DEFAULT 0,
    "error" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ProcessingJob_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "PrintShare_sharedWithUserId_idx" ON "PrintShare"("sharedWithUserId");

-- CreateIndex
CREATE UNIQUE INDEX "PrintShare_printId_sharedWithUserId_key" ON "PrintShare"("printId", "sharedWithUserId");

-- CreateIndex
CREATE INDEX "CollectionShare_sharedWithUserId_idx" ON "CollectionShare"("sharedWithUserId");

-- CreateIndex
CREATE UNIQUE INDEX "CollectionShare_collectionId_sharedWithUserId_key" ON "CollectionShare"("collectionId", "sharedWithUserId");

-- CreateIndex
CREATE INDEX "ProcessingJob_status_idx" ON "ProcessingJob"("status");

-- CreateIndex
CREATE INDEX "ProcessingJob_plateId_idx" ON "ProcessingJob"("plateId");

-- CreateIndex
CREATE INDEX "Plate_processingStatus_idx" ON "Plate"("processingStatus");

-- AddForeignKey
ALTER TABLE "PrintShare" ADD CONSTRAINT "PrintShare_printId_fkey" FOREIGN KEY ("printId") REFERENCES "Print"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PrintShare" ADD CONSTRAINT "PrintShare_sharedWithUserId_fkey" FOREIGN KEY ("sharedWithUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CollectionShare" ADD CONSTRAINT "CollectionShare_collectionId_fkey" FOREIGN KEY ("collectionId") REFERENCES "Collection"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CollectionShare" ADD CONSTRAINT "CollectionShare_sharedWithUserId_fkey" FOREIGN KEY ("sharedWithUserId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ProcessingJob" ADD CONSTRAINT "ProcessingJob_plateId_fkey" FOREIGN KEY ("plateId") REFERENCES "Plate"("id") ON DELETE CASCADE ON UPDATE CASCADE;
